spring:
  mvc:
    pathMatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev


springdoc:
  override-with-generic-response: false

app:
  file:
    upload-dir: F:/repair_tracking_app/uploads
    company-file: F:/repair_tracking_app/myCompany


jwt:
  secret: ${secret_key}